# Generated by Django 3.2.6 on 2021-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0003_game_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='game',
        ),
    ]
