# Generated by Django 3.2.6 on 2021-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0004_remove_question_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
