# Generated by Django 3.2.6 on 2021-09-12 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia_game', '0005_usergame_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_game', to='trivia_game.game'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
