# Generated by Django 3.2.6 on 2021-09-14 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0007_useranswer_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('user_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.usergame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
