# Generated by Django 3.2.6 on 2021-09-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0011_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='questions_count',
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='correct_answers',
        ),
        migrations.AlterField(
            model_name='game',
            name='no_of_participants',
            field=models.IntegerField(default=2),
        ),
    ]
