# Generated by Django 3.2.6 on 2021-09-21 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0012_auto_20210919_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usergame',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usergame',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
