# Generated by Django 3.2.6 on 2021-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0013_auto_20210921_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='no_of_participants',
            field=models.IntegerField(default=3),
        ),
    ]
